### ISSUE TITLE
[EPIC] Raise compliance from LTI 1.1 to LTI 1.3 + Advantage and pursue IMS Global certification

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks-lti-provider#45]
### Description

IMS Global has released a final candidate & reference implementation of their updated [LTI 1.3 specification](https://www.imsglobal.org/activity/learning-tools-interoperability) as well as a new security framework and three LTI Advantage extensions. We should upgrade our plugin's compliance with the new specification and [pursue official certification](https://www.imsglobal.org/learning-tools-interoperability-certification-how-and-why) from IMS Global.

**Stage 1: Research & Deepen Understanding of LTI 1.3 & outcomes/assignments**
- [x] Set up LMS implementation [Moodle &/or Canvas: https://canvas.instructure.com/login/canvas]
- [x] Get current LTI provider plugin working with outcomes (proof of concept)
- [x] Research [upgrade path from 1.1/1.2/2.0 (current) to 1.3](https://www.imsglobal.org/lti-adoption-roadmap)
* [LTI 1.3 spec](https://www.imsglobal.org/spec/lti/v1p3)
* LTI 1.3 PHP library: https://github.com/IMSGlobal/lti-1-3-php-library
* Sample WordPress multisite implementation: https://github.com/3iPunt/wordpress-lti-1-3.
* Full Ruby implementation of platform & tool: https://lti-ri.imsglobal.org/. 
- [x] Research [LTI Advantage extensions](https://www.imsglobal.org/lti-advantage-overview)
* [Assignment/Grade services](https://www.imsglobal.org/spec/lti-ags/v2p0/)
* [Name & Role provisioning](https://www.imsglobal.org/spec/lti-nrps/v2p0)
* [Deep Linking](https://www.imsglobal.org/spec/lti-dl/v2p0)

**Stage 2: Implement new security model**
- [x] [Replace PHP library with one compatible with LTI 1.3](https://github.com/pressbooks/pressbooks-lti-provider/issues/64) -- XL
- [x] [Get authentication/deep linking working with LTI 1.3 test tool](https://github.com/pressbooks/pressbooks-lti-provider/issues/67) -- XL
- [x] [Get authentication/deep linking working with LTI 1.3 provider plugin](https://github.com/pressbooks/pressbooks-lti-provider/issues/68) -- XL
* DID NOT DO: deep linking selection: make sure the user can select the page/chapter of their choice from a resource
- [x] Modify our GUI to handle new parameters [XL] https://github.com/pressbooks/pressbooks-lti-provider/issues/69
- [x] Deploy new 1.3 plugin to integrations for testing & confirm that secure launch URLs created by common cartridge work with new LTI plugin [M] https://github.com/pressbooks/pressbooks-lti-provider/issues/70
- [x] Unit tests for new plugin https://github.com/pressbooks/pressbooks-lti-provider/issues/72

**Stage 3: Assignment & Grade Services** 
- [x] Duplicate the proof of concept grade passback made for 1.1 plugin using [LTI Assignment and Grade Services Specification 2.0](https://www.imsglobal.org/spec/lti-ags/v2p0/) [L] https://github.com/pressbooks/pressbooks-lti-provider/issues/66
- [x] Write spec for desired grade reporting and UX/UI: https://github.com/pressbooks/pressbooks-lti-provider/issues/62
- [x] Build front end for grade submission: https://github.com/pressbooks/pressbooks-lti-provider-1p3/issues/8 (L)
- [x] Create table & data model for storing ALL H5P attempts by logged in users & store this data: https://github.com/pressbooks/pressbooks-lti-provider-1p3/issues/16 (M)
- [x] Unit testing pressbooks/pressbooks-lti-provider-1p3#11 + pressbooks/pressbooks-lti-provider-1p3#10

**Stage 4: Testing & Certification**
- [x] Join IMS Global 
- [x] Produce readme with instructions for installation, configuration, general use https://github.com/pressbooks/pressbooks-lti-provider-1p3/issues/22 - M
- [x] Test & document with Canvas https://github.com/pressbooks/pressbooks-lti-provider-1p3/issues/14 - M
- [x] Test & document with Moodle https://github.com/pressbooks/pressbooks-lti-provider-1p3/issues/13 - S
- [x] Test & document with D2L Brightspace https://github.com/pressbooks/pressbooks-lti-provider-1p3/issues/18 - L
- [x] Test & document with Blackboard https://github.com/pressbooks/pressbooks-lti-provider-1p3/issues/17 - L
- [ ] Test & document with Sakai https://github.com/pressbooks/pressbooks-lti-provider-1p3/issues/19 - L
- [x] Test Thin CC import and auto assignment creation: https://github.com/pressbooks/pressbooks-lti-provider/issues/80 - L
- [x] File upstream support requests for Thin CC + LTI 1.3 support: https://github.com/pressbooks/pressbooks-lti-provider-1p3/issues/28 - L
- [x] Validation improvements: https://github.com/pressbooks/pressbooks-lti-provider-1p3/issues/27 - L
- [x] Test/refine grade passback with complex situations: https://github.com/pressbooks/pressbooks-lti-provider-1p3/issues/29 - L
- [x] POTENTIAL improve unit tests to cover complex grading situations, as needed
- [x] Certify our tool (pass the tests using the [certification suite](https://ltiadvantagevalidator.imsglobal.org/ltiadv/index.html) & submit a report via [the test suite](https://apps.imsglobal.org/lti/cert/) to conformance@imsglobal.org): https://github.com/pressbooks/pressbooks-lti-provider-1p3/issues/3 - L
- [x] Deploy stable version to university.pressbooks.pub https://github.com/pressbooks/pressbooks-lti-provider-1p3/issues/48 - XL
- [ ] User creation & matching testing/comparison - https://github.com/pressbooks/pressbooks-lti-provider-1p3/issues/39 - M
- [x] Generate and store RSA key pairs: https://github.com/pressbooks/pressbooks-lti-provider-1p3/issues/58 - L

**Comment by SteelWagstaff** [comment]
More details and context available in https://docs.google.com/document/d/1C43-mCzN5UhDty_C8lh_UXoRoRKJ89-EZcdgKYYQIwo/edit (internal planning doc)

**Comment by SteelWagstaff** [comment]
TODO: work through the LTI 1.3 workflow with testing tool
- [ ] GET AUTHENTICATION WORKING
  a. start by reverse engineering their game to handle Connect LTI launch flow using LTIDeepLinkingRequest
  b. get the 'send request' step working
  c. make sure our JWT tokens are properly generated 
- [ ]  CHECK TO SEE CAN WE EMBED AN IFRAME [of the testing tool] 

ONCE TESTING TOOL WORKS -- 
- [ ] use our private plugin to make sure we can do all the previous and embed an iframe from Pressbooks
 [advanced feature, can skip] check to make sure the user can select the page/chapter of their choice from a resource
- [ ] MODIFY OUR GUI to handle new parameters
  make sure existing 'sensible defaults' plugin settings are functional with LTI 1.3
  make sure LTI consumer creation page settings work with LTI 1.3
- [ ] CHECK TO SEE that secure launch URLs created by common cartridge work with new LTI plugin

- [ ] MAKE LTI 1.3 plugin duplicate proof of concept grade passback

THEN BUILD IMPROVEMENTS IN SPEC

**Comment by SteelWagstaff** [comment]
MODIFY GUI for new parameters - XL
- [ ] Create front end
- [ ] Set up validations
- [ ] Create mechanism to post/validate
- [ ] Modify plugin to read info from metadata
